### ISSUE TITLE
Image flashes and then disappears

### ISSUE THREAD

**Issue by srikat** [nk-o/jarallax#112]
### Issue description:

Trying to get parallax effect for a section that has an image background at http://foolish-cormorant.w5.wpsandbox.pro/hello-world/. When the page loads, the image appears for a moment and goes away.

I loaded Jarallax js, assigned `jarallax` class to the background image section and added the needed CSS and init JS. These can be observed by inspecting that section and in the browser source.

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

jarallax.min.js 1.10.3.

Haven't tried the develop branch.

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<div id="section-3-10" class=" ct-section jarallax">
    <div class="ct-section-inner-wrap">
        <h1 id="headline-7-10" class="ct-headline">
            <span id="span-8-10" class="ct-span">Hello world!</span>
        </h1>
    </div>
</div>
```

```javascript
jarallax(document.querySelectorAll('.jarallax'), {
    speed: 0.2
});
```

```css
#section-3-10 {
	background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url(http://foolish-cormorant.w5.wpsandbox.pro/wp-content/uploads/2017/03/Depositphotos_30957255_original.jpg);
	background-repeat: no-repeat;
	background-color: #000000;
	text-align: center;
	background-position: 50% 50%;
}
```
