### ISSUE TITLE
background-blend-mode not working

### ISSUE THREAD

**Issue by robertsimpson** [nk-o/jarallax#114]
### Version used: 1.9

**Comment by nk-o** [comment]
Hi.

You can try to add extra styles for jarallax background:

```css
[id*="jarallax-container-"] > div {
	background-blend-mode: soft-light;
    background-color: #c36e6e;
}
```

Make sure you use background-image and not &lt;img&gt; tag when initializing jarallax (3rd example in https://github.com/nk-o/jarallax#set-up-your-html).

p.s. Multiple background images is not supported.
