### ISSUE TITLE
Keyframes & Jarallax 

### ISSUE THREAD

**Issue by Tannate** [nk-o/jarallax#124]
### Issue description:

Hello,
I have an image using your parallax effect. When I load my page, this image come up with a keyframe. The problem is that the background image position move like a glitch when I start to scroll. 
How can I fix it ?

**[Here's an exemple on JSFIDDLE](https://jsfiddle.net/uo34ru7d/37/)**

### Version used:
Last Version

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<div class="image scene_element scene_element--fadeinupimage"> </div>

</div>
<script src="https://raw.githubusercontent.com/nk-o/jarallax/master/jarallax/jarallax.js"></script>

```

```css
body {
  height:1000px;
}

.image {
  height:600px;
  width:400px;
  background-image:url("https://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg");
  margin:50px;
  position: relative;
  background-repeat: no-repeat;
    background-position: 50% 50%;
  background-size: cover;
}

@keyframes fadeInUpImage {
  0% {
   /* transform: translate3d(0, 50%, 0);*/
    opacity:0;
    transform: translateY(50%);
  }

  100% {
    opacity:1;
    transform: translateY(0px);
  }
}

.m-scene .scene_element {
  -webkit-animation-duration: 0.80s;
  animation-duration: 0.80s;
  -webkit-transition-timing-function: ease-in;
  transition-timing-function: ease-in;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both; }

.m-scene .scene_element--fadeinupimage {
  -webkit-animation-name: fadeInUpImage;
  animation-name: fadeInUpImage; }
```
