### ISSUE TITLE
Change (reload from css) image on window resize

### ISSUE THREAD

**Issue by davydkoff** [nk-o/jarallax#16]
Hello! Thanks for your work!

I have an adaptive site.
I use different images for different sizes (media queries).
How can i reload an image from css, when i change the browser window?

**Comment by nk-o** [comment]
Hi.

I think you can use destroy method. For example:

```css
.my-jarallax-section {
    position: relative;
    background-image: url(.../image-1.jpg);
}

@media (max-width: 768px) {
    .my-jarallax-section {
        background-image: url(.../image-2.jpg);
    }
}
```

```javascript
(function () {
    var $myJarallaxSection = $('.my-jarallax-section');
    var $window = $(window);

    // 768 and lower - small screen size
    var smallScreenSize = 768;
    var isSmallScreen = false;

    // init jarallax
    function initJarallax (reinit) {
        if(reinit) {
            $myJarallaxSection.jarallax('destroy');
        }
        $myJarallaxSection.jarallax();
    }
    initJarallax();

    // check if window resized
    var debounceResize;
    function resizeCheck () {
        clearTimeout(debounceResize);
        debounceResize = setTimeout(function () {
            var wndW = $window.width();
            if(isSmallScreen && wndW < smallScreenSize || !isSmallScreen && wndW >= smallScreenSize) {
                // nothing to do there
            } else {
                isSmallScreen = wndW < smallScreenSize;
                initJarallax(1);
            }
        }, 150);
    }
    $window.on('resize load orientationchange', resizeCheck);
    resizeCheck();
}());
```
